# AUTO-GENERATED by data-engine/build_lga_map.py — do not edit manually
# fmt: off

TOWER_PREFIX_TO_CITY = {'LAG': 'Lagos', 'ABJ': 'Abuja', 'KAN': 'Kano', 'POR': 'Port Harcourt', 'IBA': 'Ibadan', 'ILO': 'Ilorin', 'ENU': 'Enugu', 'BEN': 'Benin City', 'CAL': 'Calabar', 'ABA': 'Aba', 'KAD': 'Kaduna', 'WAR': 'Warri', 'ABE': 'Abeokuta', 'ONI': 'Onitsha', 'JOS': 'Jos'}

CITY_TO_LGAS = {'Lagos': ['Agege', 'Ajeromi-Ifelodun', 'Alimosho', 'Amuwo-Odofin', 'Apapa', 'Badagry', 'Epe', 'Eti-Osa', 'Ibeju-Lekki', 'Ifako-Ijaiye', 'Ikeja', 'Ikorodu', 'Kosofe', 'Lagos Island', 'Lagos Mainland', 'Mushin', 'Ojo', 'Oshodi-Isolo', 'Shomolu', 'Surulere'], 'Abuja': ['Abuja Municipal', 'Bwari', 'Gwagwalada', 'Kuje', 'Kwali', 'Abaji'], 'Kano': ['Kano Municipal', 'Fagge', 'Dala', 'Gwale', 'Tarauni', 'Nassarawa', 'Ungogo', 'Kumbotso', 'Dawakin Tofa'], 'Port Harcourt': ['Port Harcourt', 'Obio-Akpor', 'Eleme', 'Oyigbo', 'Okrika'], 'Ibadan': ['Ibadan North', 'Ibadan North-East', 'Ibadan North-West', 'Ibadan South-East', 'Ibadan South-West', 'Egbeda', 'Ona-Ara'], 'Ilorin': ['Ilorin West', 'Ilorin East', 'Ilorin South'], 'Enugu': ['Enugu North', 'Enugu South', 'Igbo-Eze North', 'Nkanu West'], 'Benin City': ['Oredo', 'Ikpoba-Okha', 'Egor', 'Ovia North-East'], 'Calabar': ['Calabar Municipal', 'Calabar South', 'Akpabuyo'], 'Aba': ['Aba North', 'Aba South', 'Osisioma'], 'Kaduna': ['Kaduna North', 'Kaduna South', 'Chikun', 'Igabi'], 'Warri': ['Warri South', 'Warri North', 'Warri South-West', 'Uvwie'], 'Abeokuta': ['Abeokuta North', 'Abeokuta South', 'Obafemi-Owode', 'Odeda'], 'Onitsha': ['Onitsha North', 'Onitsha South', 'Ogbaru', 'Oyi'], 'Jos': ['Jos North', 'Jos South', 'Riyom', 'Barkin Ladi']}

ALL_LGAS: list[str] = ['Agege', 'Ajeromi-Ifelodun', 'Alimosho', 'Amuwo-Odofin', 'Apapa', 'Badagry', 'Epe', 'Eti-Osa', 'Ibeju-Lekki', 'Ifako-Ijaiye', 'Ikeja', 'Ikorodu', 'Kosofe', 'Lagos Island', 'Lagos Mainland', 'Mushin', 'Ojo', 'Oshodi-Isolo', 'Shomolu', 'Surulere', 'Abuja Municipal', 'Bwari', 'Gwagwalada', 'Kuje', 'Kwali', 'Abaji', 'Kano Municipal', 'Fagge', 'Dala', 'Gwale', 'Tarauni', 'Nassarawa', 'Ungogo', 'Kumbotso', 'Dawakin Tofa', 'Port Harcourt', 'Obio-Akpor', 'Eleme', 'Oyigbo', 'Okrika', 'Ibadan North', 'Ibadan North-East', 'Ibadan North-West', 'Ibadan South-East', 'Ibadan South-West', 'Egbeda', 'Ona-Ara', 'Ilorin West', 'Ilorin East', 'Ilorin South', 'Enugu North', 'Enugu South', 'Igbo-Eze North', 'Nkanu West', 'Oredo', 'Ikpoba-Okha', 'Egor', 'Ovia North-East', 'Calabar Municipal', 'Calabar South', 'Akpabuyo', 'Aba North', 'Aba South', 'Osisioma', 'Kaduna North', 'Kaduna South', 'Chikun', 'Igabi', 'Warri South', 'Warri North', 'Warri South-West', 'Uvwie', 'Abeokuta North', 'Abeokuta South', 'Obafemi-Owode', 'Odeda', 'Onitsha North', 'Onitsha South', 'Ogbaru', 'Oyi', 'Jos North', 'Jos South', 'Riyom', 'Barkin Ladi']


def get_lga_for_tower(tower_id: str) -> str:
    try:
        prefix, number = tower_id.split("-")
        city = TOWER_PREFIX_TO_CITY[prefix]
        lgas = CITY_TO_LGAS[city]
        return lgas[int(number) % len(lgas)]
    except (ValueError, KeyError):
        return "Unknown"


def get_city_for_tower(tower_id: str) -> str:
    try:
        prefix = tower_id.split("-")[0]
        return TOWER_PREFIX_TO_CITY[prefix]
    except (IndexError, KeyError):
        return "Unknown"
