"""
build_lga_map.py
Hardcoded city → LGA mappings for all 15 Nigerian cities in the datasets.
Assigns tower_ids to LGAs deterministically (tower number % len(lgas)).
Outputs: data-engine/output/lga_map.py  (imported by EntityResolver)
"""

from pathlib import Path

# Tower prefix → city (derived from dataset tower_id format e.g. LAG-1234)
TOWER_PREFIX_TO_CITY: dict[str, str] = {
    "LAG": "Lagos",
    "ABJ": "Abuja",
    "KAN": "Kano",
    "POR": "Port Harcourt",
    "IBA": "Ibadan",
    "ILO": "Ilorin",
    "ENU": "Enugu",
    "BEN": "Benin City",
    "CAL": "Calabar",
    "ABA": "Aba",
    "KAD": "Kaduna",
    "WAR": "Warri",
    "ABE": "Abeokuta",
    "ONI": "Onitsha",
    "JOS": "Jos",
}

# City → LGAs (real Nigerian LGA names)
CITY_TO_LGAS: dict[str, list[str]] = {
    "Lagos": [
        "Agege", "Ajeromi-Ifelodun", "Alimosho", "Amuwo-Odofin", "Apapa",
        "Badagry", "Epe", "Eti-Osa", "Ibeju-Lekki", "Ifako-Ijaiye",
        "Ikeja", "Ikorodu", "Kosofe", "Lagos Island", "Lagos Mainland",
        "Mushin", "Ojo", "Oshodi-Isolo", "Shomolu", "Surulere",
    ],
    "Abuja": [
        "Abuja Municipal", "Bwari", "Gwagwalada", "Kuje", "Kwali", "Abaji",
    ],
    "Kano": [
        "Kano Municipal", "Fagge", "Dala", "Gwale", "Tarauni",
        "Nassarawa", "Ungogo", "Kumbotso", "Dawakin Tofa",
    ],
    "Port Harcourt": [
        "Port Harcourt", "Obio-Akpor", "Eleme", "Oyigbo", "Okrika",
    ],
    "Ibadan": [
        "Ibadan North", "Ibadan North-East", "Ibadan North-West",
        "Ibadan South-East", "Ibadan South-West", "Egbeda", "Ona-Ara",
    ],
    "Ilorin": [
        "Ilorin West", "Ilorin East", "Ilorin South",
    ],
    "Enugu": [
        "Enugu North", "Enugu South", "Igbo-Eze North", "Nkanu West",
    ],
    "Benin City": [
        "Oredo", "Ikpoba-Okha", "Egor", "Ovia North-East",
    ],
    "Calabar": [
        "Calabar Municipal", "Calabar South", "Akpabuyo",
    ],
    "Aba": [
        "Aba North", "Aba South", "Osisioma",
    ],
    "Kaduna": [
        "Kaduna North", "Kaduna South", "Chikun", "Igabi",
    ],
    "Warri": [
        "Warri South", "Warri North", "Warri South-West", "Uvwie",
    ],
    "Abeokuta": [
        "Abeokuta North", "Abeokuta South", "Obafemi-Owode", "Odeda",
    ],
    "Onitsha": [
        "Onitsha North", "Onitsha South", "Ogbaru", "Oyi",
    ],
    "Jos": [
        "Jos North", "Jos South", "Riyom", "Barkin Ladi",
    ],
}


def get_lga_for_tower(tower_id: str) -> str:
    """
    Deterministically assigns a tower_id to an LGA.
    e.g. LAG-1234 → extract prefix LAG → city Lagos → LGA by 1234 % 20
    """
    try:
        prefix, number = tower_id.split("-")
        city = TOWER_PREFIX_TO_CITY[prefix]
        lgas = CITY_TO_LGAS[city]
        return lgas[int(number) % len(lgas)]
    except (ValueError, KeyError):
        return "Unknown"


def get_city_for_tower(tower_id: str) -> str:
    try:
        prefix = tower_id.split("-")[0]
        return TOWER_PREFIX_TO_CITY[prefix]
    except (IndexError, KeyError):
        return "Unknown"


def build_tower_lga_index(tower_ids: list[str]) -> dict[str, str]:
    """Returns {tower_id: lga_id} for a list of tower IDs."""
    return {t: get_lga_for_tower(t) for t in tower_ids}


def _write_output() -> None:
    all_lgas = [lga for lgas in CITY_TO_LGAS.values() for lga in lgas]

    lines = [
        "# AUTO-GENERATED by data-engine/build_lga_map.py — do not edit manually",
        "# fmt: off",
        "",
        "TOWER_PREFIX_TO_CITY = " + repr(TOWER_PREFIX_TO_CITY),
        "",
        "CITY_TO_LGAS = " + repr(CITY_TO_LGAS),
        "",
        f"ALL_LGAS: list[str] = {repr(all_lgas)}",
        "",
        "",
        "def get_lga_for_tower(tower_id: str) -> str:",
        '    try:',
        '        prefix, number = tower_id.split("-")',
        '        city = TOWER_PREFIX_TO_CITY[prefix]',
        '        lgas = CITY_TO_LGAS[city]',
        '        return lgas[int(number) % len(lgas)]',
        '    except (ValueError, KeyError):',
        '        return "Unknown"',
        "",
        "",
        "def get_city_for_tower(tower_id: str) -> str:",
        '    try:',
        '        prefix = tower_id.split("-")[0]',
        '        return TOWER_PREFIX_TO_CITY[prefix]',
        '    except (IndexError, KeyError):',
        '        return "Unknown"',
    ]

    out = Path(__file__).parent / "output" / "lga_map.py"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"Written: {out}")
    print(f"  Cities : {len(CITY_TO_LGAS)}")
    print(f"  LGAs   : {len(all_lgas)}")


if __name__ == "__main__":
    _write_output()

    # Smoke test
    assert get_lga_for_tower("LAG-0011") == CITY_TO_LGAS["Lagos"][11 % 20]
    assert get_lga_for_tower("IKJ-9999") == "Unknown"
    print("Smoke tests passed.")
